CREATE DATABASE website;
CREATE TABLE user(user_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,login_id varchar(255) UNIQUE NOT NULL,name varchar(255)  NOT NULL,address varchar(255) NOT NULL,password varchar(255) NOT NULL, create_date DATETIME NOT NULL, update_date DATETIME NOT NULL);
CREATE TABLE item(item_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,item_name varchar(255) NOT NULL,price int NOT NULL,detail varchar(255) NOT NULL,create_date DATETIME NOT NULL, update_date DATETIME NOT NULL);
CREATE TABLE item_detail(item_detail_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT, item_id int NOT NULL,color_id int Not Null,size_id int NOT NULL, stock int not null,create_date DATETIME NOT NULL, update_date DATETIME NOT NULL);
CREATE TABLE buy(buy_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,user_id int UNIQUE Not Null,tatal_price int not null,create_date DATETIME NOT NULL);
CREATE TABLE buy_detail(buy_detail_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,buy_id int UNIQUE NOT NULL,item_id int UNIQUE NOT NULL,color_id int UNIQUE NOT NULL,size_id int UNIQUE NOT NULL,purchase_quantity int NOT NULL);
CREATE TABLE color(color_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,color_name varchar(255) UNIQUE NOT NULL);
CREATE TABLE size(size_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,size_name varchar(255) UNIQUE NOT NULL) ;
CREATE TABLE category(category_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,category_name varchar(255) UNIQUE NOT NULL);
INSERT INTO category (category_name)VALUES ('accessories');
INSERT INTO category VALUES (2,'bathmats');
select * from caregory;
delete from category where category_id=1;
drop table file;
CREATE TABLE category(category_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,category_name varchar(255) UNIQUE NOT NULL);
INSERT INTO color (color_name)VALUES ('natural');
INSERT INTO size (size_name)VALUES ('S');
CREATE TABLE favorite(favorite_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT, item_id int UNIQUE NOT NULL);
ALTER TABLE item_detail ADD item_id int NOT NULL;
CREATE TABLE file(file_id SERIAL PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT, item_detail_id int NOT NULL, file_name varchar(255) NOT NULL);
UPDATE item_detail SET size_id='3' where item_id=15;
INSERT INTO item (item_name,price,category_id,detail,create_date,update_date) VALUES ('プレミアム品質コットンタオル（3枚セット）','1790','1','タオル重量:600g/m2',NOW(),NOW());
INSERT INTO item_detail (item_id,color_id,size_id,stock,create_date,update_date) VALUES ('18','4','3','30',NOW(),NOW());
INSERT INTO file (item_detail_id,file_name) VALUES ('8','JACQUARD WAFFLE KNIT TOWEL (SET OF 2)N3.jpg');
